// POST /api/stickers/upload
// Multipart form data:
//   file: PNG / WebP / GIF (≤ 500 KB; see MAX_STICKER_SIZE_BYTES)
//   name?: optional display name (defaults to the file's base name)
//   emoji?: optional emoji (1-16 chars)
//
// Creates a Sticker row in the user's "My Uploads" pack (lazily created on
// the first upload). The pack slug is `my-uploads-<userId>` so it's unique
// per user; the storageKey is a random hex+ext generated by saveUpload() so
// the existing /api/files/<storageKey> route serves it.

import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { jsonError, tooManyRequests } from "@/lib/api";
import { getSessionUser } from "@/lib/auth";
import { saveUpload, UploadError } from "@/lib/upload";
import { uploadLimiter } from "@shared/rate-limit";
import { RATE_LIMITS, STICKER_MIME_TYPES, MAX_STICKER_SIZE_BYTES, StickerSource } from "@shared/constants";
import { toStickerDTO } from "@shared/dto";

const MY_UPLOADS_PACK_NAME = "My Uploads";

export async function POST(request: Request): Promise<NextResponse> {
  const me = await getSessionUser();
  if (!me) return jsonError(401, "Unauthorized", "UNAUTHORIZED");

  // Rate limit: same bucket as uploads (10/min/user).
  const rl = uploadLimiter.check(
    `sticker-upload:${me.id}`,
    RATE_LIMITS.upload.limit,
    RATE_LIMITS.upload.windowMs,
  );
  if (!rl.allowed) return tooManyRequests(rl.retryAfterSec);

  let formData: FormData;
  try {
    formData = await request.formData();
  } catch {
    return jsonError(400, "Expected multipart/form-data", "BAD_REQUEST");
  }

  const file = formData.get("file");
  if (!(file instanceof File)) {
    return jsonError(422, "file field is required", "VALIDATION");
  }
  if (file.size === 0) {
    return jsonError(422, "File is empty", "VALIDATION");
  }
  if (file.size > MAX_STICKER_SIZE_BYTES) {
    return jsonError(
      422,
      `Sticker must be ≤ ${Math.round(MAX_STICKER_SIZE_BYTES / 1024)} KB`,
      "TOO_LARGE",
    );
  }

  // Restrict MIME to the sticker whitelist (no PDFs, no videos).
  const mimeType = file.type || "application/octet-stream";
  if (!STICKER_MIME_TYPES.has(mimeType)) {
    return jsonError(
      422,
      `Stickers must be PNG, WebP, or GIF (got ${mimeType || "unknown"})`,
      "BAD_MIME",
    );
  }

  const name = (formData.get("name") as string | null)?.trim() || file.name.replace(/\.[^.]+$/, "");
  const emoji = (formData.get("emoji") as string | null)?.trim() || null;

  // Save the file to disk. saveUpload also enforces the global upload size
  // cap (MAX_UPLOAD_MB) and the global MIME whitelist — but our stricter
  // sticker check above already filtered out non-images.
  let stored;
  try {
    stored = await saveUpload(file, { withThumbnail: false });
  } catch (err) {
    if (err instanceof UploadError) {
      return jsonError(422, err.message, err.code);
    }
    throw err;
  }

  // Lazily create the user's "My Uploads" pack.
  const packSlug = `my-uploads-${me.id}`;
  let pack = await db.stickerPack.findUnique({ where: { slug: packSlug } });
  if (!pack) {
    pack = await db.stickerPack.create({
      data: {
        slug: packSlug,
        name: MY_UPLOADS_PACK_NAME,
        source: StickerSource.USER_UPLOAD,
        ownerId: me.id,
      },
    });
  }

  // Determine the next sortOrder within the pack.
  const maxOrder = await db.sticker.aggregate({
    where: { packId: pack.id },
    _max: { sortOrder: true },
  });
  const nextOrder = (maxOrder._max.sortOrder ?? -1) + 1;

  const sticker = await db.sticker.create({
    data: {
      packId: pack.id,
      storageKey: stored.storageKey,
      mime: stored.mimeType,
      width: stored.width ?? 256,
      height: stored.height ?? 256,
      emoji,
      sortOrder: nextOrder,
    },
    include: { pack: { select: { id: true, name: true } } },
  });

  // First sticker becomes the cover.
  if (!pack.coverStickerId) {
    await db.stickerPack.update({
      where: { id: pack.id },
      data: { coverStickerId: sticker.id },
    });
  }

  return NextResponse.json(
    { sticker: toStickerDTO(sticker, pack.name) },
    { status: 201 },
  );
}
